config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'triangle/', to: 'triangle#new'
  post 'triangle/', to: 'triangle#create'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 2 }
end

app/models/triangle.rb
class Triangle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    def new
        @comment= @post.comments.new
    end

    def create
        @comment = @post.comments.new(comment_params)
        @comment.save
        redirect_to @post
    end

    def edit
        @comment = @post.comments.find(params[:id])
    end
    
    def update
        @comment = @post.comments.find(params[:id])
        @comment.update(comment_params)
        redirect_to @post
    end
    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to @post
      end
    private
    def comment_params
        params.require(:comment).permit(:username, :body)
    end
    def set_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    def show
        @post=Post.find(params[:id])
    end
    def new
        @post=Post.new
    end
    def edit
        @post = Post.find(params[:id])
    end
    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    def destroy
        @post=Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    private
        def post_params
            params.require(:post).permit(:title, :body)
        end
end

app/controllers/triangle_controller.rb
class TriangleController < ApplicationController

    def new
    end

    def create
        @triangle = Triangle.new(params.require(:triangle).permit(:a, :b, :c))
        if  @triangle.a == @triangle.b &&  @triangle.c == @triangle.b
            @triangle.type = 'Equilateral'
        elsif  @triangle.a == @triangle.b || @triangle.b == @triangle.c || @triangle.a == @triangle.c
            @triangle.type = 'Isosceles'
        else
            @triangle.type = 'Scalene'
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/triangle_helper.rb
module TriangleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
    <strong>Username:</strong>
    <%= comment.username %>
</p>
 
<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment) %>
    <%= link_to 'Delete Comment', [comment.post, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@post,@post.comments.build ] , local: true) do |form| %>
    <p>
      <%= form.label :Username %><br>
      <%= form.text_field :username %>
    </p>
    <p>
      <%= form.label :Comment %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= form_with(model: [ @post, @comment ],  scope: :comment, url: post_comment_path, method: :put, local: true) do |form| %>
    <p>
      <%= form.label :Username %><br>
      <%= form.text_field :username %>
    </p>
    <p>
      <%= form.label :Comment %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>
<%= link_to 'Back', @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <% if @post.errors.any? %>
    <b>
    <% if @post.errors.count==1 %>
      An Error
    <% else %>
      Errors
    <% end %>
    occured while saving the post</b>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Update', edit_post_path(post) %></td>
      <td><%= link_to 'Delete', post_path(post),method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br><br>
<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1> New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Body:</b>
  <%= @post.body %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>


app/views/triangle/create.html.erb
<h1>Triangle type: <%= @triangle.type %></h1>

app/views/triangle/new.html.erb
<%= form_with scope: :triangle, local: true do |form| %>
    <p>
      <%= form.label :a %><br>
      <%= form.number_field :a, step: :any %>
    </p>
    <p>
      <%= form.label :b %><br>
      <%= form.number_field :b, step: :any  %>
    </p>
    <p>
      <%= form.label :c %><br>
      <%= form.number_field :c, step: :any  %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome Sport Compass</h1>
<p>This Application contains the following two sections:</p>
<ul>
<li><a href="http://localhost:3000/triangle" target="_blank">Triangle</li><br>
<li><a href="http://localhost:3000/posts" target="_blank">Blog API</li>
</ul>